### ISSUE TITLE
Super Admins can't see all permissions if also a Product Admin

### ISSUE THREAD

**Issue by mplt-simon** [motorpilotltd/feedback-tool#28]
If a Super Admin user is also a product Admin users then on the Users tab they only see permissions (and can revoke/edit) for users on products they are a product admin for.
They should be able to do this for everyone.

**Comment by mplt-simon** [comment]
Update to this is to adjust to allow users to be product admin of one or more products as well as a super admin. This is due to the role of product admin being used to display user details on a product page for contact purposes.

**Comment by mplt-aleks** [comment]
@mplt-simon PR is ready:

https://github.com/motorpilotltd/feedback-tool/pull/32
